# Generated by Django 4.1.7 on 2023-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
