# Generated by Django 4.1.7 on 2023-05-07 21:36

import albums.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_duration_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=75, validators=[albums.validators.validate_text]),
        ),
    ]
