# Generated by Django 4.1.7 on 2023-05-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_duration_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
