# Generated by Django 4.1.7 on 2023-05-11 10:44

import albums.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_duration_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=75, unique=True, validators=[albums.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=75, unique=True, validators=[albums.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=75, unique=True, validators=[albums.validators.validate_text]),
        ),
    ]
