# Generated by Django 4.1.7 on 2023-05-11 11:25

import albums.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_title_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(blank=True, max_length=30, validators=[albums.validators.validate_release_date]),
        ),
    ]
